global:
#  scrape_interval: 5s
  scrape_timeout: 10s
  evaluation_interval: 1m

scrape_configs:

  - job_name: 'prometheus-node-HSHP'
    scrape_interval: 15s
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'nextcloud-HSHP'
    scrape_interval: 120s
    static_configs:
      - targets: ['nextcloud-exporter:9205']

  - job_name: 'prometheus-node-Melbicom'
    scheme: https
    scrape_interval: 15s
    static_configs:
      - targets: ['xxxx.freemyip.com']

  - job_name: 'nextcloud-Melbicom'
    scheme: https
    scrape_interval: 120s
    static_configs:
      - targets: ['xxxx.freemyip.com']

  - job_name: 'cadvisor-HSHP'
    scrape_interval: 10s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'cadvisor-Melbicom'
    scheme: https
    scrape_interval: 10s
    static_configs:
      - targets: ['xxxx.freemyip.com']
