version: '3.7'

services:

#PROXY
  nginx-proxy-manager-app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm-app
    depends_on:
      - nginx-proxy-manager-db
      - nextcloud
      - portainer_agent
      - cadvisor
    ports:
      - 80:80
      - 443:443
    environment:
      MARIADB_ROOT_HOST: npm-db
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: ${DB_NPM_USER}
      DB_MYSQL_PASSWORD: ${DB_NPM_USER_PASS}
      DB_MYSQL_NAME: ${DB_NPM_NAME}
      REAL_IP_HEADER: "X-Real-IP"
      TRUSTED_PROXIES: "10.0.0.0/8, 100.64.0.0/10, 172.16.0.0/12, 192.168.0.0/16"
    volumes:
      - ./NPM:/data
      - ./NPM/letsencrypt:/etc/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - front_end
      - NPM_network
      - exporters_network

#APPS
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    depends_on:
      - db-nextcloud
    volumes:
      - ./app/config:/var/www/html/config
      - ./nextcloud:/var/www/html
      - ./app/custom_apps:/var/www/html/custom_apps
      - ./app/data:/var/www/html/data
      - ./app/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID= 1000
      - PGID= 1000
      - TZ= Europe/Moscow
      - PHP_MEMORY_LIMIT= 1G
      - PHP_UPLOAD_LIMIT= 10G
    restart: unless-stopped
    networks:
      - front_end
      - nextcloud_network

#DATA_BASES
  db-nextcloud:
    image: mariadb
    container_name: nextcloud-db
    volumes:
      - ./db-nextcloud:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD= ${DB_NC_ROOT_PASS}
      - MYSQL_USER= ${DB_NC_USER}
      - MYSQL_PASSWORD= ${DB_NC_USER_PASS}
      - MYSQL_DATABASE= ${DB_NC_NAME}
    restart: unless-stopped
    networks:
      - nextcloud_network

  nginx-proxy-manager-db:
    image: mariadb
    container_name: npm-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_NPM_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NPM_NAME}
      DB_MYSQL_PORT: 3306
      MYSQL_USER: ${DB_NPM_USER}
      MYSQL_PASSWORD: ${DB_NPM_USER_PASS}
    volumes:
      - ./NPM/NPM-db:/var/lib/mysql
    restart: unless-stopped
    networks:
      - NPM_network
#      docker restart nginx-proxy-manager-db

#EXPORTERS
  node-exporter:
    image: prom/node-exporter
    container_name: exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
    restart: unless-stopped
    environment:
      TZ: Europe/Moscow
    networks:
      - exporters_network

  portainer_agent:
    container_name: portainer_agent
    image: portainer/agent:2.19.0
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - 9001:9001
    networks:
      - exporters_network

  nextcloud-exporter: 
    image: xperimental/nextcloud-exporter:latest 
    container_name: nextcloud-exporter 
    restart: unless-stopped 
    environment:
      - NEXTCLOUD_SERVER=${NC_URL}
      - NEXTCLOUD_AUTH_TOKEN=${NC_AUTH_TOKEN}
    networks:
      - exporters_network
      - nextcloud_network

  cadvisor:
    image: 'gcr.io/cadvisor/cadvisor:latest'
    container_name: cadvisor
    expose:
      - '8080'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    restart: unless-stopped
    networks:
      - exporters_network

#NETWORKS
networks:

  front_end:
    name: front_end
    external: true

  nextcloud_network:
    name: nextcloud_network
    ipam:
      driver: default
      config:
        - subnet: 172.16.8.0/24
          ip_range: 172.16.8.0/24
          gateway: 172.16.8.1

  NPM_network:
    name: NPM_network
    ipam:
      driver: default
      config:
        - subnet: 172.16.9.0/24        
          ip_range: 172.16.9.0/24
          gateway: 172.16.9.1

  exporters_network:
    name: exporters_network
    ipam:
      driver: default
      config:
        - subnet: 172.16.10.0/24        
          ip_range: 172.16.10.0/24
          gateway: 172.16.10.1